import {Router} from 'express';
import {body} from 'express-validator';
import {validateJWT,optionalJWT} from '../middlewares/validate-jwt.js';
import {hasRoles} from '../middlewares/validate-roles.js';
import {id,validate,rejectUnsafeKeys} from '../middlewares/security.js';
import {writeLimiter} from '../middlewares/rate-limit-validator.js';
import {getHashtags,getHashtag,searchHashtags,getPublicationsByHashtag,addHashtag,deleteHashtag} from './hashtag.controller.js';
const router = Router();
router.get('/getHashtags',optionalJWT,getHashtags);
router.get('/getHashtag/:hid',optionalJWT,id('hid'),validate,getHashtag);
router.get('/search',optionalJWT,searchHashtags);
router.get('/publications/:name',optionalJWT,getPublicationsByHashtag);
router.post('/addHashtag',validateJWT,hasRoles('ADMIN'),writeLimiter,rejectUnsafeKeys,body('name').isString().bail().trim().matches(/^[a-záéíóúüñA-ZÁÉÍÓÚÜÑ0-9_]{1,40}$/),validate,addHashtag);
router.delete('/deleteHashtag/:hid',validateJWT,hasRoles('ADMIN'),writeLimiter,id('hid'),validate,deleteHashtag);
export default router;
