import {Router} from 'express';
import {body} from 'express-validator';
import {validateJWT,optionalJWT} from '../middlewares/validate-jwt.js';
import {hasRoles} from '../middlewares/validate-roles.js';
import {id,validate,rejectUnsafeKeys,loadPublication} from '../middlewares/security.js';
import {writeLimiter,uploadLimiter} from '../middlewares/rate-limit-validator.js';
import {uploadComments,storeUpload} from '../middlewares/multer-uploads.js';
import {getComments,getComment,getCommentsByPublication,addComment,deleteComment} from './comment.controller.js';
const router = Router();
router.get('/getComments',validateJWT,hasRoles('ADMIN'),getComments);
router.get('/getComment/:cid',optionalJWT,id('cid'),validate,getComment);
router.get('/publication/:pid',optionalJWT,id('pid'),validate,loadPublication,getCommentsByPublication);
router.post('/addComment',validateJWT,hasRoles('USER','ADMIN'),writeLimiter,uploadLimiter,uploadComments.single('media'),rejectUnsafeKeys,body('publication').isMongoId(),body('text').optional().isString().bail().isLength({max:500}),validate,loadPublication,storeUpload,addComment);
router.delete('/deleteComment/:cid',validateJWT,hasRoles('USER','ADMIN'),writeLimiter,id('cid'),validate,deleteComment);
export default router;
