import {Router} from 'express';
import {body} from 'express-validator';
import {validateJWT,optionalJWT} from '../middlewares/validate-jwt.js';
import {hasRoles} from '../middlewares/validate-roles.js';
import {id,validate,rejectUnsafeKeys,owner,username,email,password} from '../middlewares/security.js';
import {writeLimiter,uploadLimiter} from '../middlewares/rate-limit-validator.js';
import {uploadProfilePicture,storeUpload} from '../middlewares/multer-uploads.js';
import {updatePassword,updateUser,updateProfilePicture,deleteUser,getUsers,getUser} from './user.controller.js';
const router = Router();
router.put('/updatePassword/:uid',validateJWT,hasRoles('USER','ADMIN'),writeLimiter,id('uid'),validate,owner,rejectUnsafeKeys,body('currentPassword').isString().isLength({max:128}),password('newPassword'),validate,updatePassword);
router.put('/updateUser/:uid',validateJWT,hasRoles('USER','ADMIN'),writeLimiter,id('uid'),validate,owner,rejectUnsafeKeys,username().optional(),email().optional(),validate,updateUser);
router.patch('/updateProfilePicture/:uid',validateJWT,hasRoles('USER','ADMIN'),writeLimiter,uploadLimiter,id('uid'),validate,owner,uploadProfilePicture.single('profilePicture'),validate,storeUpload,updateProfilePicture);
router.delete('/deleteUser/:uid',validateJWT,hasRoles('USER','ADMIN'),writeLimiter,id('uid'),validate,owner,body('confirm').equals('Si'),validate,deleteUser);
router.get('/getUser/:uid',optionalJWT,id('uid'),validate,getUser);
router.get('/getUsers',validateJWT,hasRoles('ADMIN'),getUsers);
export default router;
