import {Router} from 'express';
import {body} from 'express-validator';
import {validateJWT,optionalJWT} from '../middlewares/validate-jwt.js';
import {id,validate,rejectUnsafeKeys,loadPublication} from '../middlewares/security.js';
import {writeLimiter} from '../middlewares/rate-limit-validator.js';
import {addOrUpdateReaction,removeReaction,getPublicationReactions,getUserReaction} from './reaction.controller.js';
const router = Router();
router.post('/addOrUpdateReaction/:pid',validateJWT,writeLimiter,rejectUnsafeKeys,id('pid'),body('type').isIn(['like','love','laugh','sad','angry']),validate,loadPublication,addOrUpdateReaction);
router.delete('/removeReaction/:pid',validateJWT,writeLimiter,id('pid'),validate,loadPublication,removeReaction);
router.get('/getPublicationReactions/:pid',optionalJWT,id('pid'),validate,loadPublication,getPublicationReactions);
router.get('/getUserReaction/:pid',validateJWT,id('pid'),validate,loadPublication,getUserReaction);
export default router;
