import {Router} from 'express';
import {body} from 'express-validator';
import {validateJWT,optionalJWT} from '../middlewares/validate-jwt.js';
import {hasRoles} from '../middlewares/validate-roles.js';
import {id,validate,rejectUnsafeKeys,loadPublication,editPublication} from '../middlewares/security.js';
import {writeLimiter,uploadLimiter} from '../middlewares/rate-limit-validator.js';
import {uploadPublications,storeUpload} from '../middlewares/multer-uploads.js';
import {getPublications,getPublication,getPublicationsByUser,addPublication,updatePublication,deletePublication} from './publication.controller.js';
const router = Router();
const content = optional => [body('title').isString().bail().trim().isLength({min:1,max:200}).optional(optional ? {}:false),body('description').isString().bail().trim().isLength({min:1,max:1000}).optional(optional ? {}:false),body('visibility').optional().isIn(['public','private'])];
router.get('/getPublications',optionalJWT,getPublications);
router.get('/getPublication/:pid',optionalJWT,id('pid'),validate,loadPublication,getPublication);
router.get('/user/:userId',validateJWT,id('userId'),validate,getPublicationsByUser);
router.post('/addPublication',validateJWT,hasRoles('USER','ADMIN'),writeLimiter,uploadLimiter,uploadPublications.single('media'),rejectUnsafeKeys,...content(false),validate,storeUpload,addPublication);
router.put('/updatePublication/:pid',validateJWT,hasRoles('USER','ADMIN'),writeLimiter,uploadLimiter,id('pid'),validate,loadPublication,editPublication,uploadPublications.single('media'),rejectUnsafeKeys,...content(true),validate,storeUpload,updatePublication);
router.delete('/deletePublication/:pid',validateJWT,hasRoles('USER','ADMIN'),writeLimiter,id('pid'),validate,loadPublication,editPublication,deletePublication);
export default router;
