import {Router} from 'express';
import multer from 'multer';
import {body} from 'express-validator';
import {register,login} from './auth.controller.js';
import {username,email,password,validate,rejectUnsafeKeys} from '../middlewares/security.js';
import {registerLimiter,loginLimiter} from '../middlewares/rate-limit-validator.js';
const router = Router();
router.post('/register',registerLimiter,multer({limits:{fields:8,fieldSize:1000}}).none(),rejectUnsafeKeys,username(),email(),password('password'),validate,register);
router.post('/login',loginLimiter,rejectUnsafeKeys,email().optional(),username().optional(),body('password').isString().isLength({min:1,max:128}),body().custom(data => Boolean(data.email || data.username)),validate,login);
export default router;
